/**
 * Read-only schema reference derived from backend SQLAlchemy models
 * (`backend/app/models/`). Update when models change.
 */

export type SchemaEntity = {
  tableName: string;
  modelName: string;
  purpose: string;
  primaryKey: string;
  tenantScoped: boolean;
  columns: string[];
  foreignKeys: { column: string; references: string }[];
  relationships: string[];
};

export const SCHEMA_ENTITIES: SchemaEntity[] = [
  {
    tableName: "institutions",
    modelName: "Institution",
    purpose: "Tenant root — one row per university or college.",
    primaryKey: "id",
    tenantScoped: false,
    columns: ["name", "logo_url", "description", "created_at", "updated_at"],
    foreignKeys: [],
    relationships: ["User", "Department"],
  },
  {
    tableName: "users",
    modelName: "User",
    purpose: "Login accounts scoped to an institution with a role.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "email",
      "password_hash",
      "role",
      "is_login_enabled",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [{ column: "institution_id", references: "institutions.id" }],
    relationships: ["Institution", "Student", "Faculty", "Parent"],
  },
  {
    tableName: "departments",
    modelName: "Department",
    purpose: "Academic departments within an institution.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "name",
      "code",
      "description",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
    ],
    relationships: ["Institution", "Program", "Student", "Faculty", "Course (via department_id)"],
  },
  {
    tableName: "programs",
    modelName: "Program",
    purpose: "Degree programs offered by a department.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "department_id",
      "name",
      "code",
      "duration_semesters",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "department_id", references: "departments.id" },
    ],
    relationships: ["Department", "Student"],
  },
  {
    tableName: "students",
    modelName: "Student",
    purpose: "Student academic identity linked to a user account.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "user_id",
      "roll_number",
      "name",
      "department_id",
      "program_id",
      "semester",
      "branch",
      "section",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "user_id", references: "users.id" },
      { column: "department_id", references: "departments.id" },
      { column: "program_id", references: "programs.id" },
    ],
    relationships: [
      "User",
      "Department",
      "Program",
      "Enrollment",
      "SemesterResult",
      "PredictionResult",
      "StudentGoal",
      "ParentStudent",
      "FacultyStudent",
    ],
  },
  {
    tableName: "faculty",
    modelName: "Faculty",
    purpose: "Faculty profile linked to a user account.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "user_id",
      "name",
      "department_id",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "user_id", references: "users.id" },
      { column: "department_id", references: "departments.id" },
    ],
    relationships: ["User", "Department", "FacultyCourse", "FacultyStudent"],
  },
  {
    tableName: "parents",
    modelName: "Parent",
    purpose: "Parent/guardian profile linked to a user account.",
    primaryKey: "id",
    tenantScoped: true,
    columns: ["institution_id", "user_id", "name", "created_at", "updated_at"],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "user_id", references: "users.id" },
    ],
    relationships: ["User", "ParentStudent"],
  },
  {
    tableName: "parent_students",
    modelName: "ParentStudent",
    purpose: "Links a parent to one or more students (children).",
    primaryKey: "parent_id, student_id (composite)",
    tenantScoped: false,
    columns: ["parent_id", "student_id", "created_at"],
    foreignKeys: [
      { column: "parent_id", references: "parents.id" },
      { column: "student_id", references: "students.id" },
    ],
    relationships: ["Parent", "Student"],
  },
  {
    tableName: "faculty_students",
    modelName: "FacultyStudent",
    purpose: "Mentoring link — faculty assigned to specific students.",
    primaryKey: "faculty_id, student_id (composite)",
    tenantScoped: false,
    columns: ["faculty_id", "student_id", "created_at"],
    foreignKeys: [
      { column: "faculty_id", references: "faculty.id" },
      { column: "student_id", references: "students.id" },
    ],
    relationships: ["Faculty", "Student"],
  },
  {
    tableName: "courses",
    modelName: "Course",
    purpose: "Courses/subjects offered by a department.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "department_id",
      "name",
      "code",
      "credits",
      "course_type",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "department_id", references: "departments.id" },
    ],
    relationships: ["Enrollment", "Assessment", "FacultyCourse"],
  },
  {
    tableName: "faculty_courses",
    modelName: "FacultyCourse",
    purpose: "Faculty teaching assignments for a course and semester.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "faculty_id",
      "course_id",
      "semester_id",
      "section",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "faculty_id", references: "faculty.id" },
      { column: "course_id", references: "courses.id" },
      { column: "semester_id", references: "semesters.id" },
    ],
    relationships: ["Faculty", "Course", "Semester"],
  },
  {
    tableName: "academic_years",
    modelName: "AcademicYear",
    purpose: "Academic calendar years for an institution.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "name",
      "is_current",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [{ column: "institution_id", references: "institutions.id" }],
    relationships: ["Semester"],
  },
  {
    tableName: "semesters",
    modelName: "Semester",
    purpose: "Semesters within an academic year.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "academic_year_id",
      "number",
      "name",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "academic_year_id", references: "academic_years.id" },
    ],
    relationships: ["AcademicYear", "Enrollment", "SemesterResult"],
  },
  {
    tableName: "enrollments",
    modelName: "Enrollment",
    purpose: "Student enrolled in a course for a semester; holds engagement metrics.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "student_id",
      "course_id",
      "semester_id",
      "attendance_percentage",
      "study_hours_per_week",
      "assignment_completion_pct",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "student_id", references: "students.id" },
      { column: "course_id", references: "courses.id" },
      { column: "semester_id", references: "semesters.id" },
    ],
    relationships: [
      "Student",
      "Course",
      "Semester",
      "AssessmentMark",
      "Attendance",
      "CourseResult",
    ],
  },
  {
    tableName: "assessments",
    modelName: "Assessment",
    purpose: "Assessments (e.g. CA, Mid) defined for a course.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "course_id",
      "name",
      "assessment_type",
      "max_marks",
      "date",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "course_id", references: "courses.id" },
    ],
    relationships: ["Course", "AssessmentMark"],
  },
  {
    tableName: "assessment_marks",
    modelName: "AssessmentMark",
    purpose: "Marks obtained by a student enrollment for an assessment.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "enrollment_id",
      "assessment_id",
      "marks_obtained",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "enrollment_id", references: "enrollments.id" },
      { column: "assessment_id", references: "assessments.id" },
    ],
    relationships: ["Enrollment", "Assessment"],
  },
  {
    tableName: "attendances",
    modelName: "Attendance",
    purpose: "Per-session attendance records for an enrollment.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "enrollment_id",
      "date",
      "status",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "enrollment_id", references: "enrollments.id" },
    ],
    relationships: ["Enrollment"],
  },
  {
    tableName: "course_results",
    modelName: "CourseResult",
    purpose: "Final course outcome for an enrollment (grade, end marks, pass/fail).",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "enrollment_id",
      "grade",
      "end_marks",
      "status",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "enrollment_id", references: "enrollments.id" },
    ],
    relationships: ["Enrollment"],
  },
  {
    tableName: "semester_results",
    modelName: "SemesterResult",
    purpose: "Aggregated semester metrics (SGPA, CGPA, backlogs, trends).",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "student_id",
      "semester_id",
      "sgpa",
      "cgpa",
      "backlog_count",
      "current_failed_courses",
      "low_performance_course_count",
      "performance_trend",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "student_id", references: "students.id" },
      { column: "semester_id", references: "semesters.id" },
    ],
    relationships: ["Student", "Semester"],
  },
  {
    tableName: "prediction_results",
    modelName: "PredictionResult",
    purpose: "Stored ML and risk-engine outputs per student.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "student_id",
      "semester_id",
      "predicted_end_marks",
      "pass_fail_prediction",
      "pass_probability",
      "fail_probability",
      "risk_score",
      "risk_level",
      "risk_factors",
      "recommendations",
      "input_features",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "student_id", references: "students.id" },
      { column: "semester_id", references: "semesters.id" },
    ],
    relationships: ["Student", "Semester"],
  },
  {
    tableName: "student_goals",
    modelName: "StudentGoal",
    purpose: "Student-defined academic goals and progress.",
    primaryKey: "id",
    tenantScoped: true,
    columns: [
      "institution_id",
      "student_id",
      "goal_type",
      "target_value",
      "current_value",
      "status",
      "notes",
      "created_at",
      "updated_at",
    ],
    foreignKeys: [
      { column: "institution_id", references: "institutions.id" },
      { column: "student_id", references: "students.id" },
    ],
    relationships: ["Student"],
  },
];

export function getEntityByTable(tableName: string): SchemaEntity | undefined {
  return SCHEMA_ENTITIES.find((e) => e.tableName === tableName);
}
