export const ROUTES = {
  architecture: "/architecture",
  auth: {
    login: "/login",
    signup: "/signup",
  },
  admin: {
    dashboard: "/admin/dashboard",
    profile: "/admin/profile",
    students: "/admin/students",
    faculty: "/admin/faculty",
    departments: "/admin/departments",
    programs: "/admin/programs",
    courses: "/admin/courses",
    marks: "/admin/marks",
    attendance: "/admin/attendance",
    analytics: "/admin/analytics",
    predictions: "/admin/predictions",
    atRisk: "/admin/at-risk",
    reports: "/admin/reports",
    users: "/admin/users",
  },
  student: {
    dashboard: "/student/dashboard",
    profile: "/student/profile",
    performance: "/student/performance",
    predictions: "/student/predictions",
    improvement: "/student/improvement",
    goals: "/student/goals",
    reports: "/student/reports",
  },
  faculty: {
    dashboard: "/faculty/dashboard",
    profile: "/faculty/profile",
    students: "/faculty/students",
    marks: "/faculty/marks",
    attendance: "/faculty/attendance",
    results: "/faculty/results",
    performance: "/faculty/performance",
    predictions: "/faculty/predictions",
    atRisk: "/faculty/at-risk",
    reports: "/faculty/reports",
  },
  parent: {
    dashboard: "/parent/dashboard",
    profile: "/parent/profile",
    performance: "/parent/performance",
    predictions: "/parent/predictions",
    improvement: "/parent/improvement",
    reports: "/parent/reports",
  },
} as const;
